"""add_per_subject_and_subtopic_mastery

Revision ID: ffc9450cbab4
Revises: 
Create Date: 2026-07-03 21:42:20.899652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffc9450cbab4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtopic_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('subtopic_name', sa.String(length=255), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('wrong', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtopic_mastery_id'), 'subtopic_mastery', ['id'], unique=False)

    op.add_column('analytics_results', sa.Column('physics_correct', sa.Integer(), nullable=True))
    op.add_column('analytics_results', sa.Column('physics_wrong', sa.Integer(), nullable=True))
    op.add_column('analytics_results', sa.Column('chemistry_correct', sa.Integer(), nullable=True))
    op.add_column('analytics_results', sa.Column('chemistry_wrong', sa.Integer(), nullable=True))
    op.add_column('analytics_results', sa.Column('maths_correct', sa.Integer(), nullable=True))
    op.add_column('analytics_results', sa.Column('maths_wrong', sa.Integer(), nullable=True))
    op.drop_column('analytics_results', 'estimated_percentile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_results', sa.Column('estimated_percentile', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
    op.drop_column('analytics_results', 'maths_wrong')
    op.drop_column('analytics_results', 'maths_correct')
    op.drop_column('analytics_results', 'chemistry_wrong')
    op.drop_column('analytics_results', 'chemistry_correct')
    op.drop_column('analytics_results', 'physics_wrong')
    op.drop_column('analytics_results', 'physics_correct')
    op.create_table('student_subtopic_performance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('chapter', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subtopic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_questions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wrong_questions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unattempted_questions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mastery_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('trend', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('student_subtopic_performance_student_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('student_subtopic_performance_test_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_subtopic_performance_pkey'))
    )
    op.create_index(op.f('ix_student_subtopic_performance_test_id'), 'student_subtopic_performance', ['test_id'], unique=False)
    op.create_index(op.f('ix_student_subtopic_performance_subtopic'), 'student_subtopic_performance', ['subtopic'], unique=False)
    op.create_index(op.f('ix_student_subtopic_performance_subject'), 'student_subtopic_performance', ['subject'], unique=False)
    op.create_index(op.f('ix_student_subtopic_performance_student_id'), 'student_subtopic_performance', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_subtopic_performance_id'), 'student_subtopic_performance', ['id'], unique=False)
    op.create_table('blueprint_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blueprint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('chapter', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subtopic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('marks', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difficulty_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('difficulty_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('issue_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['test_blueprints.id'], name=op.f('blueprint_questions_blueprint_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('blueprint_questions_pkey'))
    )
    op.create_index(op.f('ix_blueprint_questions_id'), 'blueprint_questions', ['id'], unique=False)
    op.create_table('student_question_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('marks_obtained', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('student_question_responses_student_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('student_question_responses_test_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_question_responses_pkey'))
    )
    op.create_index(op.f('ix_student_question_responses_id'), 'student_question_responses', ['id'], unique=False)
    op.create_table('test_blueprints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('test_blueprints_test_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('test_blueprints_pkey'))
    )
    op.create_index(op.f('ix_test_blueprints_id'), 'test_blueprints', ['id'], unique=False)
    op.drop_index(op.f('ix_subtopic_mastery_id'), table_name='subtopic_mastery')
    op.drop_table('subtopic_mastery')
    # ### end Alembic commands ###
